### ISSUE TITLE
QueryArgs

### ISSUE THREAD

**Issue by bmordan** [ghivert/elm-graphql#3]
I have got really far using this lovely library.

Thanks ghivert 🥇 

Now I want to create this query

```graphql
{
  posts(where: {search: "churches"}){
    edges{
      node{
        slug
        title
        excerpt
      }
    }
  }
}
```

I'm stuck with the `{search: "churches"}` QueryArgs. I can add a `String` to the `where` argument but have struggled with creating a QueryArgs object.

I have looked through the src code but can't find/derive an example that works.

Any pointers?

Here is my query

```elm
searchQuery : String -> Operation Query Variables
searchQuery term =
    GraphQl.named "searchQuery"
        [ GraphQl.field "posts"
            |> GraphQl.withArgument "where" (GraphQl.variable "search")
            |> GraphQl.withSelectors
                [ GraphQl.field "edges"
                    |> GraphQl.withSelectors
                        [ GraphQl.field "node"
                            |> GraphQl.withSelectors
                                [ GraphQl.field "slug"
                                ]
                        ]
                ]
        ]
        |> GraphQl.withVariables [ ( "search", "QueryArgs" ) ]


searchRequest :
    Operation Query Variables
    -> Decoder Search
    -> GraphQl.Request Query Variables Search
searchRequest =
    GraphQl.query graphqlEndpoint


sendSearch : String -> Cmd Msg
sendSearch term =
    let
        searchTerm =
            { search = term }
    in
        searchRequest (searchQuery term) decodeSearch
            |> GraphQl.addVariables [ ( "search", (Encode.encode 0 searchTerm) ) ]
            |> GraphQl.send GotSearch
```

**Comment by ghivert** [comment]
Hi, and thanks for your message!

I have a question, why not using a query like this?
```graphql
{
  posts(search: "churches") {
    edges {
      node {
        slug
        title
        excerpt
      }
    }
  }
}
```
Without the `where`? Because in this case, it seems like it does not add any information.
In your case, you should be using `input` which gives you what you want, but for the moment, it only works with mutations (because we never saw a case where it is useful in queries). Maybe it should be legal for every type of Operation?

**Comment by bmordan** [comment]
I'm using a graphql over WordPress.

```graphql
{
  "errors": [
    {
      "message": "Unknown argument \"search\" on field \"posts\" of type \"RootQuery\".",
      "category": "graphql",
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ]
    }
  ]
}
```

I did notice that and tried using input - that's what I'm after I think but for queries, not mutations. I might fork and see what I can do. Would you accept a PR if I get something working that is not too offensive?

**Comment by ghivert** [comment]
Of course! I would be glad if you can propose something working with this. :) I need to do some renaming (Value should be Field) and need to deploy a new major version, so it could be the right moment to do something like you ask ! :)
