### ISSUE TITLE
Decouple transport and query language

### ISSUE THREAD

**Issue by ulisses-alves** [ghivert/elm-graphql#5]
First, your package looks pretty neat and tidy, great job!

The only thing I would change about it would be to move all the HTTP related stuff to a separate module and then expose ways for users to extract information from the query/request so they can build their own HTTP request, WebSocket calls, or whatever else they might be using for transport.

I would even go one step further and completely remove the dependency on elm-lang/http so it becomes less opinionated, but that is just me.

**Comment by ghivert** [comment]
Hi and thanks! :)

I see your point. If the `Request` is not anymore opaque, then anyone becomes able to use the information as he want.
Do you have an example in head? Because it implies a rewrite of several things, and I want to avoid to bump a major version as long as I can.

**Comment by ulisses-alves** [comment]
I think that making the constructor public would create more harm than good because it would make it more difficult for you to later introduce non-breaking changes to the API.

Actually, the only use case I could come up with was to create a JSON payload from the Request object, so I could do my own HTTP request. That would be pretty minor considering that you already have a function for that.

**Comment by ghivert** [comment]
Yes, that's indeed the real problem.

Getting a JSON from a request is completely doable. I'll see what I can do. :)

**Comment by ulisses-alves** [comment]
Nice! Simple enough.

**Comment by ghivert** [comment]
It's mainly a workaround to get what you want, and it'll need a rewrite to be done nice (like not necessitating a decoder to extract the information), but it will wait for the v4 (when I'll fix some naming and how to do things). I'm planning to deliver it soon. :)
