### ISSUE TITLE
Encode lists

### ISSUE THREAD

**Issue by Ulrar** [ghivert/elm-graphql#6]
Hi,

I've been trying to move from jahewson/elm-graphql and I have to say I love how this lib works, way easier to use. The only thing I haven't figured out is how to properly encode objects to be sent when doing mutations. I have this : 

```elm
encodeProject : Project -> Encode.Value
encodeProject project =
  Encode.object
  [ ("assigned", Encode.list   Encode.string project.assigned)
  , ("status"  , encodeStatus  project.status)
  ]

req =
  GraphQl.named "saveProject" []
  |> GraphQl.withVariables [("project", "project")]

 GraphQl.mutation req
|> GraphQl.addVariables [("project", encodeProject project)]
|> GraphQl.Http.send ...
```

Using this the request gets sent, but my status is wrong, it's an enum, and I can't figure out a way to not have it as a string in the final json.
If instead I try to use `GraphQl.input` to generate the mutation with all the fields directly in there, which would allow me to use the type_ function for status wich I believe is what I need, I can't figure out a way to encode that list.
```elm
req =
  GraphQl.named "saveProject" []
  |> GraphQl.withArgument "project"
      (GraphQl.input
        [ ("assigned", ?)
        , ("status", GraphQl.type_ <| encodeStatus project.status)
        ]
      )
```
(I removed everything irrelevant to the issue, of course I have a lot more fields than that). What would I put instead of that '?' there ? I don't see a list primitive in the doc, as Json Encode has.
Thanks !

**Comment by ghivert** [comment]
Hi!

Thanks for your involvement with the library.  
I tried a bit with your use case, here's a typical response:

```elm
encodeStatus : Project -> String
encodeStatus project =
  String.fromInt project.status

encodeAssigned : Project -> Encode.Value
encodeAssigned project =
  Encode.list Encode.string project.assigned

operation : Operation a Variables
operation =
  GraphQl.named "SaveProject"
    [ GraphQl.field "save_project"
      |> GraphQl.withArgument "project"
          (GraphQl.input
            [ ("assigned", GraphQl.variable "assigned")
            , ("status", GraphQl.type_ <| encodeStatus sampleProject)
            ]
          )
    ]
  |> GraphQl.withVariables [ ("assigned", "[STATUS]!")]

test : Cmd Msg
test =
  GraphQl.mutation operation
  |> GraphQl.addVariables [("assigned", encodeAssigned sampleProject)]
  |> GraphQl.Http.send "#" Return (Decode.succeed ())
```

This will be transformed in:

```graphql
mutation SaveProject($assigned: [STATUS]!) {
  save_project(project: {
    assigned: $assigned, 
    status: 200
  })
}
```

And in the JSON:
```json
{
  "query": "mutation SaveProject($assigned: [STATUS]!){
      save_project(project: {
        assigned: $assigned, 
        status: 200
      })
    }",
  "variables": {
    "assigned": [ "a", "b", "c" ]
  }
}
```

And that will give you what you want.

Actually what you propose is to generate something like this:

```graphql
mutation SaveProject {
  save_project(project: {
    assigned: [ "a", "b", "c" ], 
    status: 200
  })
}
```

This means you're generating a different request each time you save a new project. That's why I didn't included a list in arguments when doing it the first time. The idea is to use majorly variables, like something like this:

```graphql
mutation SaveProject($assigned: [STATUS]!, $status: INT!) {
  save_project(project: {
    assigned: $assigned, 
    status: $status
  })
}
```

This way, you can generate your request once in your code, and just use a function which will convert your project into a JSON to use into the variables section of your app.

**Comment by Ulrar** [comment]
Oh, I see the idea, I could just have a variable for assigned but still use input for status, I suppose that's a way.
I can't use what you are proposing directly because status is an enum, not an int. It's OPEN | ARCHIVED in GraphQL, so I believe it should be `GraphQl.type_ "OPEN"` to get the propoer enum in the final json, is that correct ? If I'm not mistaken that means there is no way to decouple the json encoder for project from the mutation function request, since Json Encode doesn't have any way to generate that.

So I suppose the only way is to use input for status, and try to separately use variable and different encoders for each part of project ? I agree with you, it would be nice to generate the request once and just add variables after, but that status enum prevents me from doing that.

**Comment by Ulrar** [comment]
Also, as a bonus question, withArgument doesn't work on the request "root". I'm trying to generate something like this btw, taken from the working version I have with the other graphql lib : 

```graphql
{"query":"mutation {  saveProject(project: {assigned: [], status: OPEN}, oldName: null) {some fields here}}"}
```
I'm all for having variables instead of course, just giving you an example of what the server is expecting.

I have arguments directly on the query, I don't have sub fields, but GraphQl.named .. |> GraphQl.withArgument isn't valid. Is there a way to do this ?

**Comment by Ulrar** [comment]
And I just figured it out, I'm sorry. I was mistaking the name of the query for the name of the field, this works fine : 

```elm
saveProjectRequest =
  GraphQl.named ""
  [ GraphQl.field "saveProject"
    |> GraphQl.withArgument "project" (GraphQl.variable "project")
    |> GraphQl.withArgument "oldName" (GraphQl.variable "oldName")
  ]
```

I don't know why, I thought the argument of "named" was the name of my mutation.
