### ISSUE TITLE
[Question] How to send a request with headers?

### ISSUE THREAD

**Issue by dannyvelas** [ghivert/elm-graphql#8]
Hi,

I'm working on authentication.

In my application, after a user registers or logs in, the server sends back a token. This token is required in the headers to authenticate future queries.

How could I send headers along with GraphQl requests, to achieve this functionality?
I haven't found anything in the documentation or in the method suggestions.

Would appreciate any help. Thank you!

**Comment by ghivert** [comment]
I think it’s not possible for the moment. I’ll try to release a new version as soon as possible.

Are your authentication header `Authorize`: `Bearer xxxxxxxx`?

**Comment by ghivert** [comment]
Hi, just to let you know that I updated the package to be able to use it with the last recent version of `elm/http` and to use headers!

The new version is online at tag 5.0.0.

**Comment by dannyvelas** [comment]
Awesome thank you! Closing.
